config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :chats, only: [:new, :create, :show, :index]

  root 'chats#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_one :location, dependent: :destroy

  after_create :chat_coords

  def chat_coords
    longitude = self.longitude.to_f
    latitude = self.latitude.to_f
    self.update_attributes(longitude: longitude, latitude: latitude)
  end

  # def self.chat_radius(coord1, coord2)
  #   distance = Geocoder::Calculations.distance_between(coord1, coord2)
  #   if distance <= 10
  #     return true
  #   else
  #     return false
  #   end
  # end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chats, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :location, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @chats = Chat.all
    # @user_coords = []
    # REAL ACTUAL QUERY
    # search_result = Geocoder.search(current_user.current_sign_in_ip)
    # HARDCODED QUERY FOR TEST
    # search_result = Geocoder.search("204.57.220.1")
    # @user_coords << search_result[0].data['latitude']
    # @user_coords << search_result[0].data['longitude']
    @user_coords = [37.604683 , -122.3975142]
  end

  def new
    @chat = Chat.new
    @chat_location = request.location.coordinates
  end

  def create
    @chat = current_user.chats.build(chat_params)
    if @chat.save
      flash[:success] = 'Chat room added!'
      redirect_to chats_path
    else
      render 'new'
    end
  end

  def show
    @chat = Chat.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

private

  def chat_params
    params.require(:chat).permit(:title, :longitude, :latitude)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_chat.html.erb
 <% @chats.each do |chat| %>

 <%= [chat.longitude.to_f, chat.latitude.to_f] %>
 <%= Geocoder::Calculations.distance_between(@user_coords, [chat.longitude, chat.latitude]) %>


  <% if Geocoder::Calculations.distance_between(@user_coords, [chat.longitude.to_f, chat.latitude.to_f]) <= 100 %>
     <li><%= link_to "Enter #{chat.title}", chat_path(chat) %></li>
    <% end %>
  <% end %>

app/views/chats/index.html.erb
<h1>Chat rooms</h1>

<%= @user_coords %>


<p class="lead"><%= link_to 'New chat room', new_chat_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chats %>
</ul>

app/views/chats/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.hidden_field :longitude, value: @chat_location[0] %>
    <%= f.hidden_field :latitude, value: @chat_location[1] %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chats/show.html.erb
<h1><%= @chat.title %></h1>

<div id="messages" data-chat-id="<%= @chat.id %>">
  <%= render @chat.messages %>
</div>
<hr>

<%= form_for @message, url: '#' do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeoFrame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<nav>
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path) %>
    <%= link_to('Sign up', new_user_registration_path) %>
  <% end %>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<h3><%= message.user.name %></h3>
<p>at <%= message.timestamp %> says <%= message.body %></p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>